time is:- 2023-08-28 10:20:08.676544-04:00
trying to login
2023-08-28 10:20:08.785312-04:00  :  connected 
['BUY', 'SELL']
TOP_OPT_IMP_VOLAT_GAIN 5 BUY
scanning market
50
TOP_OPEN_PERC_LOSE 5 SELL
scanning market
Error 162, reqId 3: Historical Market Data Service error message:API scanner subscription cancelled: 3
50
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\concurrent\futures\process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Program Files\Python310\lib\concurrent\futures\process.py", line 205, in _process_chunk
    return [fn(*args) for args in chunk]
  File "C:\Program Files\Python310\lib\concurrent\futures\process.py", line 205, in <listcomp>
    return [fn(*args) for args in chunk]
  File "f:\fintech\dinesh\main.py", line 23, in process_symbols_batch
    filtered_results = filter_contracts(ibkr.ib, contracts,symbol_direction_dict)
  File "f:\fintech\dinesh\helpers\ib_func.py", line 164, in filter_contracts
    i=process_selected_item(item,symbol_direction_dict)
  File "f:\fintech\dinesh\helpers\ib_func.py", line 150, in process_selected_item
    direction=symbol_direction_dict[ticker]
TypeError: 'Contract' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "f:\fintech\dinesh\main.py", line 144, in <module>
    main_process(ibkr)
  File "f:\fintech\dinesh\main.py", line 52, in main_process
    results = list(executor.map(process_symbols_batch, symbols_batches,symbol_direction_dict))
  File "C:\Program Files\Python310\lib\concurrent\futures\process.py", line 570, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
TypeError: 'Contract' object is not subscriptable
Exception ignored in: <helpers.log.logger.<locals>.Tee object at 0x0000019D2EC7B3D0>
AttributeError: 'Tee' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'Tee' object has no attribute 'flush'
