time is:- 2023-08-28 10:29:43.613280-04:00
trying to login
2023-08-28 10:29:43.733564-04:00  :  connected 
['BUY', 'SELL']
TOP_OPT_IMP_VOLAT_GAIN 5 BUY
scanning market
50
TOP_OPEN_PERC_LOSE 5 SELL
scanning market
Error 162, reqId 3: Historical Market Data Service error message:API scanner subscription cancelled: 3
50
{Contract(secType='STK', conId=648093140, symbol='VFS', exchange='SMART', currency='USD', localSymbol='VFS', tradingClass='NMS'): 'BUY', Contract(secType='STK', conId=2586156, symbol='KMX', exchange='SMART', currency='USD', localSymbol='KMX', tradingClass='KMX'): 'BUY', Contract(secType='STK', conId=52424577, symbol='ATVI', exchange='SMART', currency='USD', localSymbol='ATVI', tradingClass='NMS'): 'BUY', Contract(secType='STK', conId=288038496, symbol='FRHC', exchange='SMART', currency='USD', localSymbol='FRHC', tradingClass='SCM'): 'BUY', Contract(secType='STK', conId=10291, symbol='NKE', exchange='SMART', currency='USD', localSymbol='NKE', tradingClass='NKE'): 'BUY', Contract(secType='STK', conId=4815747, symbol='NVDA', exchange='SMART', currency='USD', localSymbol='NVDA', tradingClass='NMS'): 'SELL', Contract(secType='STK', conId=4065, symbol='ABT', exchange='SMART', currency='USD', localSymbol='ABT', tradingClass='ABT'): 'SELL', Contract(secType='STK', conId=9720, symbol='MMM', exchange='SMART', currency='USD', localSymbol='MMM', tradingClass='MMM'): 'SELL', Contract(secType='STK', conId=326398585, symbol='PDD', exchange='SMART', currency='USD', localSymbol='PDD', tradingClass='NMS'): 'SELL', Contract(secType='STK', conId=290651477, symbol='ROKU', exchange='SMART', currency='USD', localSymbol='ROKU', tradingClass='NMS'): 'SELL'}
Traceback (most recent call last):
  File "f:\fintech\dinesh\main.py", line 146, in <module>
    main_process(ibkr)
  File "f:\fintech\dinesh\main.py", line 54, in main_process
    results = list(executor.map(process_symbols_batch, symbols_batches,symbol_direction_dict))
  File "C:\Program Files\Python310\lib\concurrent\futures\process.py", line 570, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Program Files\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
Exception ignored in: <helpers.log.logger.<locals>.Tee object at 0x000002370D05B3D0>
AttributeError: 'Tee' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'Tee' object has no attribute 'flush'
